services:
  laravel-webapp:
    build: ./WebApp
    container_name: laravel-webapp
    volumes:
      - ./WebApp:/var/www/html
      - laravel_storage:/var/www/html/storage
      - laravel_cache:/var/www/html/bootstrap/cache
    depends_on:
      - mysql
      - predict-service
    env_file:
      - .env.docker
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=laravel_db
      - DB_USERNAME=laravel_user
      - DB_PASSWORD=LaravelSecurePass2025!
      - PREDICT_SERVICE_URL=http://predict-service:5000
    networks:
      - app-network
    expose:
      - "9000"

  predict-service:
    build: ./predict-service
    container_name: predict-service
    volumes:
        - ./predict-service:/app:ro
        - ./WebApp:/var/www/html:ro
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    container_name: WebApp-db
    restart: always 
    environment:
      MYSQL_ROOT_PASSWORD: MySecureRootPass2025!
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: LaravelSecurePass2025!
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    volumes:
      - ./WebApp:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel-webapp
      - predict-service
    ports:
      - "52025:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
  laravel_storage:
  laravel_cache:

